### ISSUE TITLE
One XML points to limited time period

### ISSUE THREAD

**Issue by covey1** [pochedls/xagg#11] opened 2019-09-27 01:26 UTC
Just one of the many XMLs in /p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/zg/ points to data from the limited time period 1910-1979: CMIP6.CMIP.historical.NCC.NorESM2-LM.r1i1p1f1.mon.zg.atmos.glb-p19-gn.v20190815.0000000.0.xml. All other XMLs in this directory point to output that extends into this century. See highlighted output from my script in the attached MS Word document.
[coveyGrimTranscript.docx](https://github.com/pochedls/xagg/files/3660472/coveyGrimTranscript.docx)

**Comment by pochedls** [comment] 2019-09-27 01:43
```
$  grep directory /p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/zg/CMIP6.CMIP.historical.NCC.NorESM2-LM.r1i1p1f1.mon.zg.atmos.glb-p19-gn.v20190815.0000000.0.xml
	
directory	="/p/css03/scratch/cmip6/CMIP/NCC/NorESM2-LM/historical/r1i1p1f1/Amon/zg/gn/v20190815/"

$ ls /p/css03/scratch/cmip6/CMIP/NCC/NorESM2-LM/historical/r1i1p1f1/Amon/zg/gn/v20190815/

zg_Amon_historical_NorESM2-LM_r1i1p1f1_gn_191001-191912.nc
zg_Amon_historical_NorESM2-LM_r1i1p1f1_gn_192001-192912.nc
zg_Amon_historical_NorESM2-LM_r1i1p1f1_gn_195001-195912.nc
zg_Amon_historical_NorESM2-LM_r1i1p1f1_gn_197001-197912.nc
```

This data is still in scratch. Querying ESGF could indicate whether there is more data on another node. If there is data, Jeff or Sasha may be able to help download it here. 

@covey1 - this is the data available in that directory (so xagg is working correctly). Closing this as this doesn't appear to be a bug.

**Closed by pochedls** 2019-09-27 01:43 UTC

**Comment by durack1** [comment] 2019-09-27 02:40
@covey1 @pochedls it seems the issue is that we have a partial download of data locally, when you query the ESGF search to get at these files specifically, you can see that the data extends from 185001-201412

See https://esgf-node.llnl.gov/search/cmip6/?activity=CMIP&experiment_id=historical&source_id=NorESM2-LM&variant_label=r1i1p1f1&variable_id=zg&table_id=Amon

@painter1 what would you recommend we do to solve this issue?
